### ISSUE TITLE
[API] develop endpoint for profile wizard

### ISSUE THREAD

**Issue by dekzitfz** [yepsofficial/yeps#123]
Form di STEP 1
* browse & select skills
* browse & select interest

Form di STEP 2 (Verification Step) (isi tombol skip)
* field input NIK
* browse & upload foto KTP

**skema sync:
- sync ke API per step, dengan endpoint yg sama
- sync step 1 done, lanjut ke step 2, kirim data keseluruhan (dari step 1)
- sync step 2 done, lanjut ke step 3, kirim data keseluruhan (dari step 1 & 2)

**Comment by dekzitfz** [comment]
cuman kalo di step 2 aku pake 
"path_nik" : ""
, error dia, kayak maksa harus isi path

cc @kirizu336

**Comment by dekzitfz** [comment]
pas selesai step 2, json resultnya blm langsung nampilin skill & interest yg udah kesimpen ya? aku harus buka endpoin current user buat liat skill ama interest yg udh kesimpen

cc @kirizu336

**Comment by dekzitfz** [comment]
hasil percobaan menggunakan raw berikut:

```
{
	"step" : 2,
	"user_skill" : ["java","kotlin"],
	"user_interest" : ["sleep", "cook"],
	"nik" : ""
}
```

**Comment by dodycode** [comment]
Oke fixed, ini hasil percobaan dgn raw berikut:
```
{
  "step" : 2,
  "user_skill" : ["java","kotlin"],
  "user_interest" : ["sleep", "cook"],
  "nik" : "",
  "path_nik": ""
}
```

![screenshot_2018-07-05_06-43-33](https://user-images.githubusercontent.com/20751329/43261193-748dae84-910e-11e8-817f-0d1a3913a761.png)

![screenshot_2018-07-05_06-43-33](https://user-images.githubusercontent.com/20751329/43261354-f7a2483e-910e-11e8-977c-1f8887fc76e8.png)

Sudah berhasil langsung menampilkan interest dan skill nya (di scroll aja postman nya karna dibawah)

@dekzitfz

**Comment by dekzitfz** [comment]
siap @kirizu336
