### ISSUE TITLE
Skills & minat [API] - crawling skill from LinkedIn

### ISSUE THREAD

**Issue by gitafitria** [yepsofficial/yeps#78]

**Comment by kresnasatya** [comment]
Agak ragu ama crawling skill dan interest di linkedin, karena list nya banyak dan rasa"nya YEPS ngga semuanya mengacu pada skill dan interest di sana. Ini linknya:

https://www.linkedin.com/directory/topics

Diskusinya di Quora:
https://www.quora.com/Where-can-I-find-the-full-list-of-skills-for-the-LinkedIn-Skills-feature

Bisa pakai ruby untuk crawlingnya XD:
http://tech.bragboy.com/2016/11/crawl-all-linkedin-skills.html

**Comment by kresnasatya** [comment]
Kesimpulan: interest dan skill user di Indonesia beragam dan tidak semuanya sesuai di linkedin. Solusi: sudah dibuatkan fitur CRUD skill dan interest oleh @gitafitria .
