### ISSUE TITLE
[Landing Page] Create content

### ISSUE THREAD

**Issue by gitafitria** [yepsofficial/yeps#93]

**Comment by dodyliee** [comment]
Moto
Koneksikan dirimu dengan orang sekitarmu / Saling terhubung dengan orang sekitarmu
Konten web :
1.Fitur nearby
Fitur ini memungkinkan pengguna YEPS terkoneksi secara mudah dengan pengguna lainya yang di sekitarnya, dan juga mengetahui profil seperti Biodata, pengalaman, keahlian, dan  pencapaian yang dimiliki pengguna tersebut. Tidak hanya itu saja, para pengguna juga dapat terhubung dengan komunitas lokal dan pengguna yang memiliki minat yang sama.
2.Fitur mentoring,
Dengan mengajak pengguna saling berbagi pada kelas prifat yang dibuka dalam fitur mentoring, kini para pengguna YEPS dapat mendapatkan penghasilan sendiri dari Keahlian dan pengalaman yang dimiliki.
3.Get your JOB.
Dengan data pencapaian, keahlian dan pengalaman yang terdata pada aplikasi YEPS, para pengguna mampu terkoneksi dengan beberapa program lokal dan instansi  yang membutuhkan tenaga ahli sesuai dengan kriteria yang diinginkan.
