### ISSUE TITLE
Google Account Login [API] - endpoint

### ISSUE THREAD

**Issue by gitafitria** [yepsofficial/yeps#98]

**Comment by kresnasatya** [comment]
Untuk Google login via Firebase ini, apa aja key dan value dari Firebase yang bisa kita simpan di table user? Jadi, pada saat user login (kedua kali dst) lewat Google maka kita akan cek menggunakan key dan value yang sudah ada. Tlng dijabarkan apa nama key dan valuenya. Trims.
